# Generated by Django 5.2.7 on 2025-10-31 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_person_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'مرد'), ('F', 'زن')], max_length=1),
        ),
    ]
