# Generated by Django 5.2.7 on 2025-10-31 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0003_alter_person_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'مرد'), ('F', 'زن')], max_length=1, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='person',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children_of', to='family.person', verbose_name='والدین'),
        ),
        migrations.AlterField(
            model_name='person',
            name='spouses',
            field=models.ManyToManyField(blank=True, related_name='spouse_of', to='family.person', verbose_name='همسران'),
        ),
    ]
